import React, { useEffect, useState, useCallback } from "react";
import { getInsights } from "../../api/AiApi";
import Navbar from "../../components/Navbar";

const AIInsights = () => {
  const token = localStorage.getItem("access");
  const [insights, setInsights] = useState("");

  // Memoize the loadInsights function
  const loadInsights = useCallback(async () => {
    try {
      const res = await getInsights(token);
      setInsights(res.data.insights);
    } catch (err) {
      console.log(err);
      alert("Unable to load insights");
    }
  }, [token]); // token is a dependency

  useEffect(() => {
    loadInsights();
  }, [loadInsights]); // now safe to include

  return (
    <>
      <Navbar />
      <div className="container mt-5" style={{ maxWidth: "900px" }}>
        <h2 className="fw-bold text-primary mb-4">📈 AI Financial Insights</h2>

        {!insights ? (
          <div className="alert alert-info">⏳ Loading insights, please wait...</div>
        ) : (
          <div className="card shadow-sm border-0">
            <div className="card-header bg-primary text-white fw-semibold">
              💡 Smart Insights Generated by AI
            </div>

            <div className="card-body">
              <pre
                style={{
                  whiteSpace: "pre-wrap",
                  fontSize: "1rem",
                  lineHeight: "1.6",
                }}
                className="mb-0"
              >
                {insights}
              </pre>
            </div>
          </div>
        )}
      </div>
    </>
  );
};

export default AIInsights;
